INSERT INTO tbl_teacherHours_2014_2015 (TEACHER_ID, COURSE_ID, RESPONSIBLE_FOR_COURSE, LECTURED_HOURS)
(SELECT DISTINCT TEACHER_CODE, COURSE_CODE, RESPONSIBLE_FOR_COURSE, SUM(LECTURED_HOURS)
FROM tbl_PROFESSORSHIP
WHERE EXECUTION_YEAR = 9
GROUP BY TEACHER_CODE, COURSE_CODE)