insert into tbl_professorship 
(COURSE_CODE, TEACHER_CODE, DEGREE_CODE, EXECUTION_YEAR, SEMESTER, LECTURED_HOURS,
RESPONSIBLE_FOR_COURSE, BEGIN_DATE, END_DATE)
select a.COURSE_CODE, b.ID, a.DEGREE_CODE, a.EXECUTION_YEAR, a.SEMESTER, a.LECTURED_HOURS,
a.RESPONSIBLE_FOR_COURSE, a.BEGIN_DATE, a.END_DATE
from tbl__professorship as a join tbl_teacher as b on a.TEACHER_CODE = b.ID