insert into tbl_teacher 
(ID, CATEGORY, FULL_NAME, MILITARY_SITUATION, ID_NUMBER, CONTRACT, BEGIN_DATE, END_DATE, E_MAIL,
MOBILE_PHONE, SCIENTIFIC_FIELD, ACADEMIC_DEGREE, CATEGORY_DATE, IN_CHARGE, CATEGORY_GROUP_ID,
MASTER_DEGREE_ID)
select ID, CATEGORY, FULL_NAME, MILITARY_SITUATION, ID_NUMBER, CONTRACT, BEGIN_DATE, END_DATE, E_MAIL,
MOBILE_PHONE, SCIENTIFIC_FIELD, ACADEMIC_DEGREE, CATEGORY_DATE, IN_CHARGE, CATEGORY_GROUP_ID,
MASTER_DEGREE_ID from tbl__teacher